name: Java CI
on:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: JasonEtco/upload-to-release@master
      with:
        args: target/DanceInterpreter-full.jar application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
