name: Release Jar
on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn install --file pom.xml
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project
    - name: Show extracted Maven project version
      run: echo ${{ steps.project.outputs.version }}
    - name: Upload Jar to Release
      if: github.event_name == 'release'
      uses: JasonEtco/upload-to-release@master
      with:
        args: target/danceinterpreter-${{ steps.project.outputs.version }}-full.jar application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload deb to Release
      if: github.event_name == 'release'
      uses: JasonEtco/upload-to-release@master
      with:
        args: target/danceinterpreter-${{ steps.project.outputs.version }}_all.deb application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload rpm to Release
      if: github.event_name == 'release'
      uses: JasonEtco/upload-to-release@master
      with:
        args: target/danceinterpreter-${{ steps.project.outputs.version }}-1.noarch.rpm application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload exe to Release
      if: github.event_name == 'release'
      uses: JasonEtco/upload-to-release@master
      with:
        args: target/danceinterpreter-${{ steps.project.outputs.version }}.exe application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
